#pragma once

#define EXPORT_FUNCTION extern "C" __declspec(dllexport)

EXPORT_FUNCTION void lua_close() {}
EXPORT_FUNCTION void lua_newthread() {}
EXPORT_FUNCTION void lua_atpanic() {}
EXPORT_FUNCTION void lua_rotate() {}
EXPORT_FUNCTION void lua_rawlen() {}
EXPORT_FUNCTION void lua_absindex() {}
EXPORT_FUNCTION void lua_gettop() {}
EXPORT_FUNCTION void lua_settop() {}
EXPORT_FUNCTION void lua_pushvalue() {}
EXPORT_FUNCTION void lua_isnumber() {}
EXPORT_FUNCTION void lua_isinteger() {}
EXPORT_FUNCTION void lua_isstring() {}
EXPORT_FUNCTION void lua_iscfunction() {}
EXPORT_FUNCTION void lua_isuserdata() {}
EXPORT_FUNCTION void lua_type() {}
EXPORT_FUNCTION void lua_tonumberx() {}
EXPORT_FUNCTION void lua_tointegerx() {}
EXPORT_FUNCTION void lua_toboolean() {}
EXPORT_FUNCTION void lua_tolstring() {}
EXPORT_FUNCTION void lua_tocfunction() {}
EXPORT_FUNCTION void lua_touserdata() {}
EXPORT_FUNCTION void lua_pushnil() {}
EXPORT_FUNCTION void lua_pushnumber() {}
EXPORT_FUNCTION void lua_pushinteger() {}
EXPORT_FUNCTION void lua_pushlstring() {}
EXPORT_FUNCTION void lua_pushstring() {}
EXPORT_FUNCTION void lua_pushcclosure() {}
EXPORT_FUNCTION void lua_pushboolean() {}
EXPORT_FUNCTION void lua_pushlightuserdata() {}
EXPORT_FUNCTION void lua_gettable() {}
EXPORT_FUNCTION void lua_rawgeti() {}
EXPORT_FUNCTION void lua_createtable() {}
EXPORT_FUNCTION void lua_newuserdata() {}
EXPORT_FUNCTION void lua_getmetatable() {}
EXPORT_FUNCTION void lua_settable() {}
EXPORT_FUNCTION void lua_rawseti() {}
EXPORT_FUNCTION void lua_setmetatable() {}
EXPORT_FUNCTION void lua_callk() {}
EXPORT_FUNCTION void lua_pcallk() {}
EXPORT_FUNCTION void lua_load() {}
EXPORT_FUNCTION void lua_dump() {}
EXPORT_FUNCTION void lua_gc() {}
EXPORT_FUNCTION void lua_error() {}
EXPORT_FUNCTION void lua_next() {}
EXPORT_FUNCTION void lua_setglobal() {}
EXPORT_FUNCTION void lua_getglobal() {}
EXPORT_FUNCTION void lua_getinfo() {}
EXPORT_FUNCTION void lua_getlocal() {}
EXPORT_FUNCTION void lua_sethook() {}
EXPORT_FUNCTION void luaL_argerror() {}
EXPORT_FUNCTION void luaL_ref() {}
EXPORT_FUNCTION void luaL_unref() {}
EXPORT_FUNCTION void luaL_loadfilex() {}
EXPORT_FUNCTION void luaL_loadstring() {}
EXPORT_FUNCTION void luaL_newstate() {}
EXPORT_FUNCTION void luaL_openlibs() {}
